language: cpp
branches: 
  only: 
    - master
    - dev
dist: trusty
os: 
  - linux
addons: 
  apt: 
    packages: 
      - cmake-data
      - cmake
      - clang-6.0
      - libboost1.58-dev
      - libboost-system1.58-dev
      - libboost-filesystem1.58-dev
      - libboost-serialization1.58-dev
      - libboost-log1.58-dev
      - lcov
    sources:
      - ubuntu-toolchain-r-test 
      - george-edison55-precise-backports
      - llvm-toolchain-trusty-6.0
      - sourceline: 'ppa:kojoley/boost'
    env:
      - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
before_install:
      - eval "${MATRIX_EVAL}"
before_script: 
  - "mkdir build"
  - "cd build"
  - "cmake .. -DCMAKE_BUILD_TYPE=Debug"
script: make
