language: cpp
branches: 
  only: 
    - master
    - dev
compiler: 
  - clang
dist: trusty
os: 
  - linux
addons: 
  apt: 
    packages: 
      - cmake-data
      - cmake
      - clang-5.0
      - libboost-all-dev
    sources: 
      - george-edison55-precise-backports
      - llvm-toolchain-trusty-5.0
before_script: 
  - "mkdir build"
  - "cd build"
  - "cmake .."
script: make
