theme: jekyll-theme-minimal
show_downloads: true
git_branch: master
title: G³M a flexible groundwater framework
description: Written in C++, with openMP support, developed in Frankfurt a.M., Germany

google_analytics: UA-109358361-1
show_downloads: true
